/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kuglvzsxwmmdaewhrtht"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z2x2enN4d21tZGFld2hydGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTU0NjksImV4cCI6MjA2OTI3MTQ2OX0.vX8t7uEaNFrTfn-hA0j_uR-CFUh3RXFhYVd9gNiDmbk"